### ISSUE TITLE
Resizing crashes

### ISSUE THREAD

**Issue by matkuki** [TerryGeng/termqt#6]
When resizing the window larger<>smaller a couple of times, this error gets thrown (reproducible on Windows):
```
[2023-05-09 20:24:38,544] > [terminal_buffer.py:717] screen: resize triggered, new size (99x31)
Traceback (most recent call last):
  File "J:\Python\termqt\termqt\terminal_widget.py", line 152, in resizeEvent
    self.resize(event.size().width(), event.size().height())
  File "J:\Python\termqt\termqt\terminal_widget.py", line 298, in resize
    self._restore_cursor_state()
  File "J:\Python\termqt\termqt\terminal_widget.py", line 365, in _restore_cursor_state
    self._switch_cursor_blink(self._cursor_blinking_state, True)
  File "J:\Python\termqt\termqt\terminal_widget.py", line 356, in _switch_cursor_blink
    self._paint_cursor()
  File "J:\Python\termqt\termqt\terminal_widget.py", line 259, in _paint_cursor
    qp.fillRect(x, y, cw, ch, bg)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRect, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'float'
```

**Comment by TerryGeng** [comment]
https://github.com/TerryGeng/termqt/blob/7a61d9c5838ed389d7d69f678f64f206bb48dd91/termqt/terminal_widget.py#LL259C42-L259C42

Can you try replacing the `x` and `y` with `int(x)`, `int(y)`?
